### PR TITLE
Revert Emails to basic text to pass spam filters

### PR DESCRIPTION
**Pull request by jake-percentageproject**
Something about the CSS and HTML styling was causing this to go to spam. I reverted to basic text so we at least have our basic needs met. Styling changes on temples should all pass a spam filter check before merging.

### CODE REVIEW

**Comment by jake-percentageproject** [comment]
This is an easy merge so if someone wants to suggest more sophisticated text i'm happy to add it in to this PR.

**Comment by jake-percentageproject** [comment]
Screen Shot 2020-10-10 at 7 26 56 PM

**Comment by jake-percentageproject** [comment]
Screen Shot 2020-10-10 at 7 27 33 PM

**Review by gfting — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
